create table tasks (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50) NOT NULL,
description VARCHAR(250) NOT NULL,
status VARCHAR(50) NOT NULL,
creation_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);